---
- name: Install Splunk Forwarder
  hosts: all
  become: yes  # Use sudo privileges

  tasks:
    - name: install pexpect library
      pip:
        name: pexpect
      become: yes

    - name: Upload Splunk .rpm
      copy:
        src: upload-files/splunkforwarder-9.1.2-b6b9c8185839.x86_64.rpm
        dest: /home/ec2-user/splunkforwarder-9.1.2-b6b9c8185839.x86_64.rpm

    - name: Install RPM package and create /opt/splunkforwarder
      shell: rpm -i /home/ec2-user/splunkforwarder-9.1.2-b6b9c8185839.x86_64.rpm

    - name: Upload inputs.conf
      copy:
        src: upload-files/inputs.conf
        dest: /opt/splunkforwarder/etc/system/local/inputs.conf

    - name: Upload outputs.conf
      copy:
        src: upload-files/outputs.conf
        dest: /opt/splunkforwarder/etc/system/local/outputs.conf

    - name: Start Splunk forwarder service.
      expect:
        command: /opt/splunkforwarder/bin/splunk start --accept-license
        timeout: 60
        responses:
           (.*)Please enter an administrator username(.*): "procore"
           (.*)Please enter a new password(.*): "Welcome2VITI!"
           (.*)Please confirm new password(.*): "Welcome2VITI!"
    
    - name: Check Splunk forwarder service.
      command:
        /opt/splunkforwarder/bin/splunk status
      register: service_splunk_status
    