---
- name: Upload Splunk Config files and start
  hosts: all
  become: yes  # Use sudo privileges

  tasks:
    - name: install pexpect library
      pip:
        name: pexpect
      become: yes

    - name: Upload inputs.conf
      copy:
        src: upload-files/inputs.conf
        dest: /opt/splunkforwarder/etc/system/local/inputs.conf

    - name: Upload outputs.conf
      copy:
        src: upload-files/outputs.conf
        dest: /opt/splunkforwarder/etc/system/local/outputs.conf

    - name: Start Splunk forwarder service.
      expect:
        command: /opt/splunkforwarder/bin/splunk start --accept-license
        timeout: 60
        responses:
           (.*)Please enter an administrator username(.*): "procore"
           (.*)Please enter a new password(.*): "Welcome2VITI!"
           (.*)Please confirm new password(.*): "Welcome2VITI!"
    
    - name: Check Splunk forwarder service.
      command:
        /opt/splunkforwarder/bin/splunk status
      register: service_splunk_status